speedtest.o:speedtest.cc btree.h btree_multimap.h skiplist.h skiplist_multimap.h nv_backend.h
		g++ -g -O3 speedtest.cc -lvmem -lpmem -lc -fpermissive -std=c++11 -Wno-deprecated -o test
clean:
		rm -rf test
